# render.yaml - Must be at the root of your repository

databases:
  # PostgreSQL Database
  - name: document_management_db
    databaseName: document_management
    user: postgres

services:
  # Redis Cache (using Docker)
  - type: pserv
    name: document_management_redis
    runtime: docker
    image: redis:7-alpine
    plan: starter
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

  # Django Web Service
  - type: web
    name: backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "cd backend && daphne document_management.asgi:application -b 0.0.0.0 -p $PORT"
    healthCheckPath: "/admin/login/"
    plan: starter
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document_management_db
          property: connectionString
      - key: REDIS_URL
        value: redis://document_management_redis:6379
      - key: SECRET_KEY
        generateValue: true
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-document-index
      - key: GEMINI_API_KEY
        sync: false
    preDeployCommand: "cd backend && python manage.py migrate"

  # Django RQ Worker
  - type: worker
    name: background_document_management_task
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python manage.py rqworker default"
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document_management_db
          property: connectionString
      - key: REDIS_URL
        value: redis://document_management_redis:6379
      - key: SECRET_KEY
        generateValue: true
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-document-index
      - key: GEMINI_API_KEY
        sync: false