# render.yaml - Must be at the root of your repository

databases:
  # PostgreSQL Database (Free tier)
  - name: document_management_db
    databaseName: document_management
    plan: free

services:
  # Django Web Service
  - type: web
    name: backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "cd backend && daphne document_management.asgi:application -b 0.0.0.0 -p $PORT"
    healthCheckPath: "/admin/login/"
    plan: free
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document_management_db
          property: connectionString
      - key: REDIS_URL
        value: ""  # Empty for free tier - app will handle gracefully
      - key: SECRET_KEY
        generateValue: true
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-document-index
      - key: GEMINI_API_KEY
        sync: false