# render.yaml - Must be at the root of your repository

services:
  # PostgreSQL Database
  - type: pserv
    name: document_management_db
    env: postgres
    plan: starter
    # region: oregon

  # Redis Cache
  - type: pserv
    name: document_management_redis
    env: redis
    plan: starter

  # Django Web Service
  - type: web
    name: backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "cd backend && daphne document_management.asgi:application -b 0.0.0.0 -p $PORT"
    healthCheckPath: "/admin/login/"
    plan: starter
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document_management_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: document_management_redis
          property: connectionString
          type: pserv
      - key: SECRET_KEY
        generateValue: true
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-document-index
      - key: GEMINI_API_KEY
        sync: false
    preDeployCommand: "cd backend && python manage.py migrate"

  # Django RQ Worker
  - type: worker
    name: background_document_management_task
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python manage.py rqworker default"
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: document_management_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: document_management_redis
          property: connectionString
          type: pserv
      - key: SECRET_KEY
        generateValue: true
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-document-index
      - key: GEMINI_API_KEY
        sync: false