# Generated by Django 5.2.5 on 2025-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
