# Generated by Django 5.2.5 on 2025-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_file_path_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
